---
title: "Huanyu Chen's Resume"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
editor_options: 
  markdown: 
    wrap: 72
---

# Education

**Columbia University**, Mailman School of Public Health

*M.S. in Biostatistics*

-   Related Coursework: Survival Analysis, Data Science, Biostatistics
    Method

**University of Rochester**

*B.S. in Pure Mathematics; B.A. in Statistics; and B.A. in Economics*

-   David T. Kearns Scholar

-   Teaching Assistant: Fall 2022 in Statistics Dept. & Spring 2021 in
    Economics Dept.

-   Related Coursework: Intro to Statistical Software SAS, Sampling
    Techniques

# Professional Experience

**Yunji Sharing Technology Co., Ltd**

*Assistant Consultant (Full-Time Intern)*

A leading company of membership E-business in China; NASDAQ code: YJ.

-   Analyzed data of customers using R to identify more effective ways
    of marketing and contributed to sales of over 200,000 products and
    earned over 5,000,000 RMB during summer 2021.

-   Processed identity data of over 2000 people in Excel by using
    functions including v-lookup and PivotTable.

**Beijing Hopu Youxue Education Technology Co., Ltd.**

*Part-Time Instructor*

-   Provide online courses to over 200 students in probability,
    mathematical statistics, and GRE math.

# RESEARCH

**Big Data for Health Equity**

*Undergraduate Researcher*, Advisor: Prof. Thu Nguyen - University of
Maryland

-   Collected more than 100,000 data via CrowdTangle on national liberal
    and conservative news media posts from 2015 to 2022; filtered and
    cleaned data based on keywords related to race and health.

-   Participated in a retrospective cohort study utilized R in
    investigating the area-level racial bias of racism and its
    association with mental and physical health outcomes.

**STEM For All:** Natural Language Processing and Reinforcement Learning

*Undergraduate Researcher*, Advisor: Prof. Alex Iosevich - University of
Rochester

[link](https://people.math.rochester.edu/faculty/iosevich/projects2022.html)

-   Developed a mechanism mainly utilizing support vector machine
    methods to quickly identify the academic department of a university
    page and the news outlet of a front-page story, showcasing
    interdisciplinary application of reinforcement learning techniques.

**Summer Institute in Computational Social Science**

*Undergraduate Researcher*, Advisor: Prof. Cantay Caliskan - University
of Rochester

[link](https://sicss.io/2022/rochester/)

-   Crawled more than 130,000 users from Bēhance; analyzed uploaders and
    estimated recommended algorithms; conducted network analysis using
    Cytoscape and performed data grouping using Python.

-   Final project paper achieved first place in the assessment.

# Contact Information

-   [Github](https://github.com/JessicaChenHuanyu)
-   [Email](mailto:hc3451@cumc.columbia.edu)
-   [LinkedIn](https://www.linkedin.com/in/huanyu-chen-5785151a1/)
